Controllers/ConfiguracoesController.cs
using PowerOne.Models;
using PowerOne.Repository;
using PowerOne.Util;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Web.Hosting;
using PortalMOB.Repositories.Interfaces;
using PortalMOB.Models;

namespace PowerOne.Controllers
{
    //[Authorize]
    public class ConfiguracoesController : Controller
    {
        //#region Serviços
        //private ConfiguracoesService _configuracoesService = new ConfiguracoesService();
        //private AutorizacoesService _autorizacoesService = new AutorizacoesService();
        //private ProjetosService _projetosService = new ProjetosService();
        //private LicencaService _licencaService = new LicencaService();
        //private CRMService _CRMService = new CRMService();
        //private AtividadeService _atividadeService = new AtividadeService();
        //private LoginService _loginService = new LoginService();
        //#endregion
        private readonly IConfiguracoesRepository _configuracoesRepository;

        public ConfiguracoesController(
        IConfiguracoesRepository configuracoesRepository)
        {
            _configuracoesRepository = configuracoesRepository;
        }


        #region Configurar Email
        //public ActionResult Email()
        //{
        //    if (((Login)Session["auth"]).Autorizacoes.Tipo != "Adm")
        //    {
        //        return RedirectToAction("NaoAutorizado", "Home");
        //    }

        //    ConfiguracoesEmail configuracoesEmail = _configuracoesService.GetConfiguracoesEmail();

        //    return View(configuracoesEmail);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Email(ConfiguracoesEmail configEmail)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(configEmail);
        //    }

        //    string msg = _configuracoesService.ConfigurarEmail(configEmail);

        //    if (msg != null)
        //    {
        //        TempData["Error"] = msg;
        //        Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
        //    }
        //    else
        //    {
        //        TempData["Success"] = "Email Configurado com Sucesso!";
        //    }

        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Anexo(ConfiguracoesEmail confAnexo)
        //{
        //    string msg = _configuracoesService.ConfiguraAnexo(confAnexo);

        //    if (msg != null)
        //    {
        //        TempData["Error"] = msg;
        //        Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
        //    }
        //    else
        //    {
        //        TempData["Success"] = "Anexos do Email Configurados com Sucesso!";
        //    }

        //    return RedirectToAction(nameof(Email));
        //}
        #endregion

        #region Temas
        public ActionResult Temas()
        {
            return View();
        }

        #endregion



        #region Configurar Modelos RPT para impressao
        //public ActionResult
        //    ConfigurarModelosImpressao(
        //    HttpPostedFileBase solicitacao,
        //    HttpPostedFileBase pedido,
        //    HttpPostedFileBase nfentrada,
        //    HttpPostedFileBase requerimentoEstoque,
        //    HttpPostedFileBase reembolso)
        //{
        //    string msg = null;

        //    try
        //    {
        //        if (solicitacao != null)
        //        {
        //            string fileName = Path.GetFileName(solicitacao.FileName);
        //            string path = Path.Combine(Server.MapPath("~/Files/RPT"), fileName);

        //            // salva o modelo na pasta de ~/Files/RPT do portal
        //            solicitacao.SaveAs(path);

        //            // pega só diretório do arquivo para salvar no SAP
        //            string dirPath = Path.Combine("~/Files/RPT", fileName);

        //            msg = _configuracoesService.ConfigurarModeloImpressao("SC", "Modelo p/ Solicitação de Compras", dirPath);
        //        }
        //        else if (pedido != null)
        //        {
        //            string fileName = Path.GetFileName(pedido.FileName);
        //            string path = Path.Combine(Server.MapPath("~/Files/RPT"), fileName);

        //            // salva o modelo na pasta de ~/Files/RPT do portal
        //            pedido.SaveAs(path);

        //            // pega só diretório do arquivo para salvar no SAP
        //            string dirPath = Path.Combine("~/Files/RPT", fileName);

        //            msg = _configuracoesService.ConfigurarModeloImpressao("PC", "Modelo p/ Pedido de Compra", dirPath);
        //        }
        //        else if (requerimentoEstoque != null)
        //        {
        //            string fileName = Path.GetFileName(requerimentoEstoque.FileName);
        //            string path = Path.Combine(Server.MapPath("~/Files/RPT"), fileName);

        //            // salva o modelo na pasta de ~/Files/RPT do portal
        //            requerimentoEstoque.SaveAs(path);

        //            // pega só diretório do arquivo para salvar no SAP
        //            string dirPath = Path.Combine("~/Files/RPT", fileName);

        //            msg = _configuracoesService.ConfigurarModeloImpressao("RE", "Modelo p/ Requerimento de Estoque", dirPath);
        //        }
        //        else if (reembolso != null)
        //        {
        //            string fileName = Path.GetFileName(reembolso.FileName);
        //            string path = Path.Combine(Server.MapPath("~/Files/RPT"), fileName);

        //            // salva o modelo na pasta de ~/Files/RPT do portal
        //            reembolso.SaveAs(path);

        //            // pega só diretório do arquivo para salvar no SAP
        //            string dirPath = Path.Combine("~/Files/RPT", fileName);

        //            msg = _configuracoesService.ConfigurarModeloImpressao("RB", "Modelo p/ Reembolso", dirPath);
        //        }
        //        else if (nfentrada != null)
        //        {
        //            string fileName = Path.GetFileName(nfentrada.FileName);
        //            string path = Path.Combine(Server.MapPath("~/Files/RPT"), fileName);

        //            // salva o modelo na pasta de ~/Files/RPT do portal
        //            nfentrada.SaveAs(path);

        //            // pega só diretório do arquivo para salvar no SAP
        //            string dirPath = Path.Combine("~/Files/RPT", fileName);

        //            msg = _configuracoesService.ConfigurarModeloImpressao("NE", "Modelo p/ Nota fiscal entrada", dirPath);
        //        }
        //    }
        //    catch (Exception e)
        //    {
        //        msg = e.Message;
        //    }

        //    if (msg != null)
        //    {
        //        TempData["Error"] = msg;
        //        Log.Gravar(msg, Log.TipoLog.Erro);
        //    }
        //    else
        //    {
        //        TempData["Success"] = "Modelos para impressão de Documentos definidos com sucesso!";
        //    }

        //    return RedirectToAction(nameof(DocConfig));
        //}
        #endregion

        #region DOWNLOAD ARQUIVO RPT
        //public ActionResult DownloadRPT(string code)
        //{
        //    try
        //    {
        //        string file_path = _configuracoesService.GetDiretorioModeloImpressao(code);
        //        string name = Path.GetFileName(file_path);

        //        //FileIOPermission writePermission = new FileIOPermission(FileIOPermissionAccess.Write, file_path);
        //        //if (writePermission.AllFiles == System.Security.Permissions.FileIOPermissionAccess.AllAccess)
        //        //{
        //        //    throw new Exception("Não é possível fazer o download, permissão de leitura não concedida");
        //        //}

        //        return File(file_path, "application/rpt", name);
        //    }
        //    catch (Exception e)
        //    {
        //        TempData["Error"] = e.Message;
        //        return RedirectToAction("DocConfig");
        //    }
        //}

        //private Exception Exception(string v)
        //{
        //    throw new NotImplementedException();
        //}

        #endregion

        #region Trocar Icones
        //[HttpPost]
        //public ActionResult ChangeIcons(string icon)
        //{
        //    if (icon != null)
        //    {
        //        string msg = _configuracoesService.ConfigurarTema(((Models.Login)Session["auth"]).Id.ToString(), null, icon);

        //        if (msg != null)
        //        {
        //            TempData["Error"] = msg;
        //            Log.Gravar(msg, Log.TipoLog.Erro);
        //        }
        //        else
        //        {
        //            ((Models.Login)Session["auth"]).Tema = _configuracoesService.GetTema(((Models.Login)Session["auth"]).Id.ToString());
        //            TempData["Success"] = "icones alterados com sucesso!";
        //        }
        //    }
        //    else
        //    {
        //        TempData["Error"] = "Selecione um icone!";
        //        Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
        //    }

        //    return RedirectToAction(nameof(Temas));
        //}
        #endregion

        #region Upload de Logo
        //[HttpPost]
        //public ActionResult UploadLogo(HttpPostedFileBase logo)
        //{
        //    string msg = null;
        //    try
        //    {
        //        if (logo != null)
        //        {
        //            string path = Path.Combine(Server.MapPath("~/Content/img"), "logo-company.png");
        //            logo.SaveAs(path);
        //        }
        //    }
        //    catch (Exception e)
        //    {
        //        msg = e.Message;
        //    }

Controllers/LoginController.cs
using System;
using System.Data;
using System.Net.Mail;
using System.Web.Mvc;
using System.Web.Security;
using Antlr.Runtime.Misc;
using Microsoft.Ajax.Utilities;
using PowerOne.Models;
using PowerOne.Repository;
using PowerOne.Util;
using System.Timers;
using PowerOne.Models.ViewModel;
using PortalMOB.Repositories.Interfaces;
using DAL;
using Utils;

namespace PowerOne.Controllers
{
    public class LoginController : Controller
    {
        #region Intancing Repositories 
        private readonly ILoginRepository _loginRepository;
        private readonly IConfiguracoesRepository _configuracoesRepository;
        private readonly IAutorizacoesRepository _autorizacoesRepository;

        public LoginController(
            ILoginRepository loginRepository,
            IAutorizacoesRepository autorizacoesRepository,
            IConfiguracoesRepository configuracoesRepository)
        {
            _loginRepository = loginRepository;
            _autorizacoesRepository = autorizacoesRepository;
            _configuracoesRepository = configuracoesRepository;
        }
        #endregion         

        #region GET Login 
        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region POST Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Login login)
        {

            if (!ModelState.IsValid)
            {
                return View(login);
            }

            string validado = isValid(login);
            if (validado == "Valid")
            {

                FormsAuthentication.SetAuthCookie(login.email, false);

                if (login.Password.ToUpper() == "NOVO")
                {
                    return RedirectToAction(nameof(AlterarSenha));
                }

                return RedirectToAction("Index", "Home");
            }   
            else
            {
                ModelState.AddModelError("email", "Email e/ou Senha incorreto(s)!");
                return View();
            }

        }
        #endregion

        #region Validação
        private string isValid(Login login)
        {
            string valid = null;

            #region consulta se cadastro ja existe funcionario

            int id_User = 0;
            id_User = _loginRepository.ConsultaId(login); /*consulta o Id da OHEM*/
            if (id_User != 0)
            {
                bool temCadastro = _loginRepository.ConsultaCadastro(id_User); /*consulta na P1_ACESS o id*/
                if (!temCadastro)
                {
                    string msg = _loginRepository.AddAcess(login, id_User); /*add caso nao exista*/
                }
            }
            #endregion

            Login user = _loginRepository.Login(login);

            if (user != null)
            {
                LoginDAL loginServiceLayer = new LoginDAL();
                // define tema
                Tema tema = _configuracoesRepository.GetTema(user.UserId.ToString());
               
                valid = "Valid";
                if (tema != null)
                {
                    user.Tema = tema;
                }
                else
                {
                    _configuracoesRepository.ConfigurarTema(user.UserId.ToString(), "RED", "PRO");
                    user.Tema = _configuracoesRepository.GetTema(user.UserId.ToString());
                }

                //_autorizacoesRepository.CriarAutorizacoes(user);
                user.Autorizacoes = _autorizacoesRepository.PegarAutorizacoes(user.UserId.ToString());
                user.Autorizacoes.Grupo = _autorizacoesRepository.PegarGrupoAutorizacoes(user.Autorizacoes);
                user.MACaddress = _loginRepository.GetMacAddress().ToString();
                user.sessionId = LoginDAL.sessionId;
                
                Session["auth"] = user;
                //ConstantUtils.SESSION = user;
                //ConstantUtils.AUTHORIZATIONS = user.Autorizacoes;
            }
            return valid;
        }
        #endregion

        #region Alteração de Senha
        public ActionResult AlterarSenha()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AlterarSenha(AlterarSenhaViewModel alterarSenha)
        {
            Login user;

            if (!ModelState.IsValid)
            {
                return View(alterarSenha);
            }

            Login paramsLogin = new Login() { email = alterarSenha.email, User = alterarSenha.CodPNLink, Password = alterarSenha.CurrentPassword };
            user = _loginRepository.Login(paramsLogin);
      
            if (user != null)
            {
                _loginRepository.EditarSenha(alterarSenha);

                Session["auth"] = user;
            }
            else
            {
                ModelState.AddModelError("CurrentPassword", "Senha atual incorreta!");
                return View(alterarSenha);
            }

            TempData["Success"] = "Senha alterada com sucesso!";
            return RedirectToAction("Logout");
        }
        #endregion

        #region Recuperar Senha
        public ActionResult RecuperarSenha()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RecuperarSenha(RecuperarSenhaViewModel recuperarSenha)
        {
            if (!ModelState.IsValid)
            {
                return View(recuperarSenha);
            }

            ConfiguracoesEmail configEmail = _configuracoesRepository.GetConfiguracoesEmail();
            string IdUser = _loginRepository.GetIdUsuarioPorEmail(recuperarSenha.Email);
            if (String.IsNullOrEmpty(IdUser))
            {
                ModelState.AddModelError("Email", "Os dados inseridos não correspondem a um usuário cadastrado, VerIfique seu cadastro no SAP!");
                return View(recuperarSenha);
            }
            else
            {
                //editar senha
                AlterarSenhaViewModel paramsPassword = new AlterarSenhaViewModel()
                {
                    Id = int.Parse(IdUser),
                    //gerando senha com 10 caracteres
                    NewPassword = GeradorDeSenha.GetSenha(10)
                };

                _loginRepository.EditarSenha(paramsPassword);
                //_email.RecoverPasswordEmail(paramsPassword.NewPassword, recuperarSenha.Email, configEmail);

                TempData["Success"] = "Você recebeu um email com sua nova senha!";
            }
            return RedirectToAction("Index");
        }
        #endregion

        #region Logout
        public ActionResult Logout()
        {
            //string aux = _loginService.logoutLogLogin((Login)Session["auth"]);
            FormsAuthentication.SignOut();           

            return Redirect(nameof(Index));
        }
        #endregion
  
    }
}

Views/Shared/_Layout.cshtml
@{
    PowerOne.Models.Autorizacoes autorizacoes = ((PowerOne.Models.Login)Session["auth"]).Autorizacoes;
}

<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title</title>

    <link rel="manifest" href="~/Content/manifest.json">
    <link rel="icon" type="image/png" href="~/Content/img/icon-192x192.png">

    @Styles.Render("~/Content/css")
    @*@Styles.Render("~/Content/js")*@
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" type="text/css" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src="~/Content/popper.min.js"></script>

    @if (Session["auth"] != null)
    {
        if (((PowerOne.Models.Login)Session["auth"]).Tema != null)
        {
            if (((PowerOne.Models.Login)Session["auth"]).Tema.Color != null)
            {
                <link rel="stylesheet" type="text/css" href="~/Content/var-css/@(((PowerOne.Models.Login)Session["auth"]).Tema.Color.ToString()).css">
            }
            else
            {
                <link rel="stylesheet" type="text/css" href="~/Content/var-css/BLACK.css">
            }

        }
        else
        {
            <link rel="stylesheet" type="text/css" href="~/Content/var-css/BLACK.css">
        }
    }
    else
    {
        <link rel="stylesheet" type="text/css" href="~/Content/var-css/BLACK.css">
    }

</head>
<body>
    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="border-right" id="sidebar-wrapper">
            <div class="sidebar-heading list-group">
                <a href="~/">
                    <img class="m-auto col-10 py-3" src="~/Content/img/logo-company.png" />
                </a>
            </div>
            <div class="list-group list-group-flush">
                <div class="accordion" id="sidebar">
      

                        @if (
                            (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.ReqEstoque != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.ReqEstoque != "N")
                            ||
                            (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.CriarReqEstoque != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.CriarReqEstoque != "N")
                            )
                        {
                            @Html.ActionLink("Estoque", "Estoque", "Home", null, new { @class = "list-group-item list-group-item-action" })
                        }

          
                        @if
                 (
                   (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.LancamentoDesp == "T")
                   ||
                   (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.PrestacaoContas == "T")
                   ||
                   (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.ReqEstoque == "T")
                 )
                        {

                            @Html.ActionLink("Aprovação/Autorização", "Index", "Aprovacao", null, new { @class = "list-group-item list-group-item-action" })
                        }

                        @Html.ActionLink("Configurações", "Configuracoes", "Home", null, new { @class = "list-group-item list-group-item-action" })
                        @Html.ActionLink("Sair", "Logout", "Login", null, new { @class = "list-group-item list-group-item-action" })

                </div>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="row">
                <div class="col-10 d-inline">
                    <button class="btn m-3 " id="menu-toggle">
                        <span>&#9776;</span>
                    </button>
                </div>
            </div>

            <div class="container-fluid">
                @if (String.IsNullOrEmpty(ViewBag.Title))
                {
                    <label class="ml-2 voltarLayout d-inline " onclick="window.history.go(-1);">/ Voltar </label>
                }
                @RenderBody()

            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>

    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <!-- Global site tag (gtag.js) - Google Analytics -->
    @*<script async src="https://www.googletagmanager.com/gtag/js?id=UA-178729722-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-178729722-1');
    </script>*@
    

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    @*<script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>*@

    <script src="~/Content/main.js"></script>

    @RenderSection("scripts", required: false)

    <script>

        // Define o intervalo de duração na tela de todos as alertas do Portal
        $(function () {
            setTimeout(function () {
                $('.alert').hide();
            }, 4000);
        });



        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

        $("#checkTodos").change(function () {
            $("input:checkbox.cbx-billmessage").prop('checked', $(this).prop("checked"));
        });

        $("#checkTodos").change(function () {
            $("input:checkbox.cbx-reqestoque").prop('checked', $(this).prop("checked"));
        });

        $('#nav-anexos-tab').click(function () {
            $('#form_anexo').show();
            $('#form_item').hide();
            $('#div_processo').hide();
        });

        $('#nav-itens-tab').click(function () {
            $('#form_anexo').hide();
            $('#div_processo').hide();
            $('#form_item').show();
        });

        $('#nav-processo-tab').click(function () {
            $('#div_processo').show();
            $('#form_anexo').hide();
            $('#form_item').hide();
        });

        var editor = new MediumEditor('.editable', {
            imageDragging: false,
            toolbar: {
                buttons: [
                    'bold',
                    'italic',
                    'underline',
                    'strikethrough',
                    'anchor',
                    'orderedlist',
                    'unorderedlist',
                    'indent',
                    'outdent',
                    'justifyLeft',
                    'justifyCenter',
                    'justifyRight',
                    'justifyFull',
                    'h1',
                    'h2',
                    'h3',
                    'h4',
                    'h5',
                    'h6',
                    'removeFormat',
                    'html '
                ]
            }
        });



    </script>
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
<html>
<head>
    <link rel="icon" type="image/png" href="~/Content/img/icon-192x192.png">
    <meta name="viewport" content="width=device-width" />
    <title>Login - Portal Unificado</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="bg-body-login">
    <main class="container-fluid">
        @RenderBody()
    </main>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>